version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "Anthony5265"
  - package-ecosystem: npm
    directory: "/apps/actions-api"
    schedule:
      interval: weekly
    reviewers:
      - "Anthony5265"
  - package-ecosystem: npm
    directory: "/mobile"
    schedule:
      interval: weekly
    reviewers:
      - "Anthony5265"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "Anthony5265"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "Anthony5265"
