name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs: 
  chatgpt-review:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@b3

      - name: ChatGPT CodeReviewer
        uses: anc95/ChatGPT-CodeReview@v1.0.22
        with:
          openai_key: ${{ secrets.OPENAI_API_KEY }}
