name: Gitleaks
on:
  workflow_dispatch: null
  pull_request: null
  push:
    branches:
    - main
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: zricethezav/gitleaks-action@v2
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
