name: GPT Comment Density Analyzer

on:
  workflow_dispatch:
  pull_request:

jiobs:
  comment-density:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze comment desity
        run: grep -r "#" . /
        gpt=("Is the comment to code ratio adequate and well-balanced?", "user")
        curl -HX Authorization: Bearer { { secrets.OPENAI_API_KEY }} --data {"model": "gpt-4", "messages": [{"role": "user", "content": "${gpt}"}]}