name: GPT README Enhancer

on:
  workflow_dispatch:
  pull_request:

jiobs:
  readme-enancer:
    runs-on: ubuntu-latest
    steps: 
      - name: Enhance README with GOPT-
        run: cat README.md
        gpt=("Can you enhance this README file to be more user-friendly and descriptive for new comers?", "user")
        curl -HX Authorization: Bearer { { secrets.OPENAI_API_KEY } } --data '{"model": "gpt-4", "messages": [{"role": "user", "content": "${gpt}"}]}'