name: GPT Regression Risk Detector

on:
  workflow_dispatch:
  pull_request:

jiobs:
  regression:
    runs-on: ubuntu-latest
    steps:
    - name: Detect Regression Risk
        run: git diff --cache
        gpt=("What are the risks of regression as per this diff and code base?", "user")
        curl -HX Authorizition: Bearer { { secrets.OPENAI_API_KEY } } --data '{"model": "gpt-4", "messages": [{"role": "user", "content": "${gpt}"}]}
